# Details about the site
site_name: "Proactive Programmers"
site_url: https://www.proactiveprogrammers.com
repo_url: https://github.com/ProactiveProgrammers/www.proactiveprogrammers.com

# Copyright of the site appears in the footer
# copyright: Copyright &copy; 2021 Gregory M. Kapfhammer
# copyright: 'Deploys by <a href = "https://www.netlify.com/" rel="noopener" target="_blank">Netlify</a>'

# Definition of the theme
theme:
  # Use the default theme and then customize it further
  name: material
  # Provide an overrides/ directory that contains a main.html file for customization
  custom_dir: overrides
  # Define the logo for the top left-hand corner of the screen and collapsible menu
  logo: img/Pro-Icon.svg
  # Define the favicon that displays in the tab of the browser
  favicon: img/Pro-Favicon.png
  # Define the logo for the repository for the top right-hand corner of the screen
  icon:
      repo: fontawesome/brands/github
  # Define the fonts used on the site
  font:
      # The main font used in header, footer, and all body text
      text: IBM Plex Sans
      # The font used in all of the source code samples
      code: IBM Plex Mono
  # Create black menu bars at the top and bottom
  palette:
    - scheme: default
      primary: black
      accent: orange
  # Enable features that are built-in to material for mkdocs
  features:
      # Note that this option prohibits the rendering of mathematics
      # - navigation.instant
      # Display tabs for main sections at top of page
      - navigation.tabs
      # Automatically expand the navigation for each section
      # Note that this might not be suitable for courses with many assignments
      # - navigation.expand
      # Offer a "Back to Top" button when person starts scrolling up on page
      - navigation.top
      # Make search suggestions when using project-wide search
      - search.suggest
      # Enable the sharing of searches with an icon in search box after start
      - search.share
      # Highlight search terms that match on the chosen page
      - search.highlight

# Extensions to markdown that provide the feature described above the extension itself
markdown_extensions:
    # Add HTML attributes and CSS classes to markdown elements
    - attr_list
    # Support the inclusion of snippets of HTML or Markdown from other files;
    # note that this extension also enables the chosen abbreviations approach
    - pymdownx.snippets:
    # Display and generate emojis using the standard notation (e.g., ":runner:")
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    # Display mathematics using MathJax
    - pymdownx.arithmatex:
          generic: true
    # Display paragraph markers that exhibit as permalinks for section in a file
    - toc:
        permalink: true
    # Highlight source code
    - codehilite
    - markdown.extensions.codehilite:
        guess_lang: true
    # Admonitions in separate boxes
    - admonition
    # Make admonitions collapsible
    - pymdownx.details
    # Support extra social media icons in the footer
    - extra
    # Display keys with easier-to-read symbols
    - pymdownx.keys
    # Allow jump-to-and-jump back footnotes
    - footnotes
    # Display diagrams created with mermaid
    # Note that this works in conjunction with mermaid2
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_div_format
    # Enable source code and admonitions to be tabbed
    - pymdownx.tabbed
    # Provide support for more intelligent emphasis and bolding
    - pymdownx.betterem:
        smart_enable: all
    # Support highlighting of text and super- and sub-scripts
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    # Support inserting special characters with greater ease
    - pymdownx.smartsymbols
    # Support the creation of customizable task lists
    - pymdownx.tasklist:
        custom_checkbox: true

# Install plugins
plugins:
  - search
  - mermaid2

# Add icons and links to the footer
extra:
  social:
    # GitHub organization
    - icon: fontawesome/brands/github
      link: https://github.com/ProactiveProgrammers
    # GitHub issue tracker
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ProactiveProgrammers/www.proactiveprogrammers.com/issues
    # GitHub discussions
    - icon: fontawesome/solid/comments
      link: https://github.com/ProactiveProgrammers/www.proactiveprogrammers.com/discussions
    # Slack workspace (open to allegheny.edu by default)
    - icon: fontawesome/brands/slack
      link: https://proactiveprogrammers.slack.com
    # Discord server invitation (open publicly)
    - icon: fontawesome/brands/discord
      link: https://discord.gg/kjah8MFYbR
    # Twitter account
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ProactiveProgr3

# Load the stylesheet that overrides parts of the material for mkdocs theme
extra_css:
  - stylesheets/extra.css

# Load the JavaScript needed to support MathJax rendering inside of site
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Page tree that defines the navigation structure
nav:
  - Home: index.md
  - Proactive Skills:
    - Technical Skills:
      - Introduction: proactive-skills/technical-skills/introduction-technical-skills.md
      - Using Terminal: proactive-skills/technical-skills/using-terminal.md
      - Using Docker: proactive-skills/technical-skills/using-docker.md
      - Using Git: proactive-skills/technical-skills/using-git.md
    - Professional Skills:
      - Introduction: proactive-skills/professional-skills/introduction-professional-skills.md
      - Effective Communication: proactive-skills/professional-skills/effective-communication.md
      - Time Management: proactive-skills/professional-skills/time-management.md
      - Reading Documentation: proactive-skills/professional-skills/reading-documentation.md
  - Proactive Community:
    - Introduction: proactive-community/introduction-proactive-community.md
    - Technical Resources: proactive-community/technical-resources.md
    - Professional Resources: proactive-community/professional-resources.md
    - Community Connections: proactive-community/community-connections.md
  - Proactive Learning:
    - Introduction: proactive-learning/introduction-proactive-learning.md
    - Bloom's Taxonomy: proactive-learning/blooms-taxonomy.md
    - Assignment Types: proactive-learning/assignment-types.md
    - Assessment Strategy: proactive-learning/assessment-strategy.md
  - Data Abstraction:
    - Introduction: data-abstraction/introduction-data-abstraction.md
    - Learning Objectives: data-abstraction/learning-objectives-data-abstraction.md
    - Source Code Surveys:
      - Number Squaring: data-abstraction/source-code-surveys/number-squaring.md
      - Primality Testing: data-abstraction/source-code-surveys/primality-testing.md
      - Exhaustive Enumeration: data-abstraction/source-code-surveys/exhaustive-enumeration.md
    - Programming Projects:
      - Iteration Comparison: data-abstraction/programming-projects/iteration-comparison.md
      - Maximum Detection: data-abstraction/programming-projects/maximum-detection.md
      - Bisection Search: data-abstraction/programming-projects/bisection-search.md
    - Engineering Efforts:
      - Software Tools: data-abstraction/engineering-efforts/software-tools.md
      - Repairing Iteration: data-abstraction/engineering-efforts/repairing-iteration.md
      - Newton-Raphson Method: data-abstraction/engineering-efforts/newtons-method.md
  - Discrete Structures:
    - Introduction: discrete-structures/introduction-discrete-structures.md
    - Learning Objectives: discrete-structures/learning-objectives-discrete-structures.md
    - Source Code Surveys:
      - Averaging Values: discrete-structures/source-code-surveys/averaging-values.md
      - File Searching: discrete-structures/source-code-surveys/file-searching.md
      - Approximate Roots: discrete-structures/source-code-surveys/approximate-roots.md
    - Programming Projects:
      - Temperature Conversion: discrete-structures/programming-projects/temperature-conversion.md
      - Contact Searching: discrete-structures/programming-projects/contact-searching.md
      - Factorial Numbers: discrete-structures/programming-projects/factorial-numbers.md
    - Engineering Efforts:
      - Software Tools: discrete-structures/engineering-efforts/software-tools.md
      - Quadratic Roots: discrete-structures/engineering-efforts/quadratic-roots.md
      - Iterative Exponentiation: discrete-structures/engineering-efforts/iterative-exponentiation.md
