[build.environment]
  NODE_VERSION = "16"
  PYTHON_VERSION = "3.8"

[build]
publish = "site"
command = """
pip install -q poetry &&
poetry config virtualenvs.in-project true &&
poetry install -v &&
ENABLE_PDF_EXPORT=1 mkdocs build -d site &&
jupyter lite build --output-dir live
cd decks
cd data-abstraction-slides
npm install
npm run build --workspaces
cd ..
cd discrete-structures-slides
npm install
npm run build --workspaces
"""
