[build]
publish = "site"
command = """
pip install -q poetry &&
poetry config virtualenvs.in-project true &&
poetry install -v &&
mkdocs build -d site
"""

[[redirects]]
  from = "/decks/week-one"
  to = "https://simple-slidev-decks.netlify.app/week-one/"
  status = 301
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/decks/week-two"
  to = "https://simple-slidev-decks.netlify.app/week-two/"
  status = 301
  force = true # COMMENT: ensure that we always redirect
