[build.environment]
  NODE_VERSION = "14"

[build]
publish = "site"
command = """
pip install -q poetry &&
poetry config virtualenvs.in-project true &&
poetry install -v &&
mkdocs build -d site
cd decks
npx pnpm install --recursive --store=node_modules/.pnpm-store && npx pnpm run build
"""
