[build]
publish = "site"
command = """
pip install -q poetry &&
poetry config virtualenvs.in-project true &&
poetry install -v &&
mkdocs build -d site
"""

[[redirects]]
  from = "/decks/*"
  to = "https://simple-slidev-decks.netlify.app/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect

# [[redirects]]
#   from = "/decks/week-"
#   to = "https://simple-slidev-decks.netlify.app/week-two/"
#   status = 200
#   force = true # COMMENT: ensure that we always redirect
