[build.environment]
  NODE_VERSION = "16"

[build]
publish = "site"
command = """
pip install -q poetry &&
poetry config virtualenvs.in-project true &&
poetry install -v &&
mkdocs build -d site
cd decks
cd data-abstraction-slides
npm install
npm run build --workspaces
"""
