blank_issues_enabled: false
contact_links:
  - name: I have a technical question or need technical support with content on Proactive Programmers
    url: https://github.com/ProactiveProgrammers/www.proactiveprogrammers.com/discussions
    about: We use GitHub Discussions for all detailed communication about technical content. No invitation needed!
  - name: I have a quick technical question about the content on Proactive Programmers
    url: https://discord.com/invite/kjah8MFYbR
    about: If you have a quick question, then joining our Discord Chat is a great idea. Just ask for an invitation!
  - name: I am an Allegheny College student and I have a quick technical question about the content on Proactive Programmers
    url: https://discord.gg/3AzphUqEBQ
    about: If you have a quick question and are a student at Allegheny College, then using the private Discord Chat is a great idea.
  - name: I heard about Proactive Programmers but I don't know how to find it!
    url: https://proactiveprogrammers.com/
    about: If you want to access the technical content, then visit the main web site!
  - name: I'm unsure where to go for more help with Proactive Programmers
    url: https://discord.com/invite/kjah8MFYbR
    about: If you are unsure where to go, then joining our Discord chat is recommended. Just ask for an invitation!
