# Details about the site
site_name: "Proactive Programmers"
site_url: https://www.proactiveprogrammers.com
repo_url: https://github.com/ProactiveProgrammers/www.proactiveprogrammers.com

# Copyright of the site appears in the footer
copyright: Copyright &copy; 2020 - 2021 Gregory M. Kapfhammer

# Definition of the theme
theme:
  # Use the default theme and then customize it further
  name: material
  # Provide an overrides/ directory that contains a main.html file for customization
  custom_dir: overrides
  # Define the logo for the top left-hand corner of the screen and collapsible menu
  logo: img/Pro-Icon.svg
  # Define the logo for the repository for the top right-hand corner of the screen
  icon:
      repo: fontawesome/brands/github
  # Define the fonts used on the site
  font:
      # The main font used in header, footer, and all body text
      text: IBM Plex Sans
      # The font used in all of the source code samples
      code: IBM Plex Mono
  palette:
    - scheme: default
      primary: black
      accent: orange
  features:
      - navigation.instant
      - navigation.top
      - search.suggest
      - search.share

markdown_extensions:
    - attr_list
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.arithmatex:
          generic: true
    - toc:
        permalink: true
    - markdown.extensions.codehilite:
        guess_lang: false
    - admonition
    - codehilite
    - extra
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_div_format
    - pymdownx.tabbed

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ProactiveProgrammers
    - icon: fontawesome/brands/slack
      link: https://github.com/ProactiveProgrammers
    - icon: fontawesome/brands/discord
      link: https://github.com/ProactiveProgrammers

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
